- ppp/iteration_1_18102022.md
> docs: first lol ppp

- .github/workflows/ci.yml
- bors.toml
Add bors and 'lint-commit' job
> CI improvements

- pubspec.lock
Bump minor versions of Flutter packages.
> chore: Update pubspec.lock

- ppp/iteration_2_24102022.md
> docs: second lol ppp

- .github/workflows/flutter_android_test.yml
At the same time, attempt to utilise caching.
> chore(ci): Update java version in Android end-to-end job

- Makefile
- README.md
- rust/Cargo.toml
- bump Rust edition to 2021
- add convenience lint stage for easy static analysis
- add `make fmt` alias for formatting
- mention rust-flutter-bridge docs
> Small project setup improvements

- integration_test/main.dart
- integration_test/off_topic_code.dart
- lib/dashboard.dart
- lib/main.dart
- lib/mocks.dart
- lib/off_topic_code.dart
- lib/seed.dart
- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/api.rs
- rust/src/lib.rs
- rust/src/seed.rs
- rust/src/wallet.rs
This PR derives a BIP84 wallet from a BIP39 seed phrase and exposes a corresponding rust api through the flutter rust bridge. Additionally this PR already improves the structuring (to the best of my limited flutter skills).
resolves #68 #11 
This PR is still draft as the seed screen needs a little bit more care.
> BIP39 derived seed for a BIP84 wallet

- .gitignore
- Makefile
- integration_test/off_topic_code.dart
- lib/ffi.io.dart
- lib/ffi.web.dart
- lib/off_topic_code.dart
- rust/src/bridge_generated/mod.rs
@klochowicz I am still in favor of this for the reason as described in 77f66274da07d4cd2f556e73a53f9924fa902153
> Change target directory of generated code

- lib/main.dart
- rust/src/api.rs
- rust/src/wallet.rs
See commit description for details.
> Fix a few things inside wallet

- Makefile
- README.md
- Add a simple menu to the most useful commands (to improve discoverability).
- Add a new `make all` command to do the whole dev cycle (codegen + rust + flutter)
- mention the improvements in the docs.
> chore: Improve Makefile

- ios/Podfile.lock
- lib/main.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
This will allow to log messages using the FLog, which allows to export any logs to file.
resolves #103
> Log dart messages to file

- macos/Podfile.lock
- macos/Runner.xcodeproj/project.pbxproj
After re-building the project, this change comes up.
> chore: Update flutter macOS boilerplate

- lib/dashboard.dart
- lib/main.dart
- lib/receive.dart
- lib/send.dart
- macos/Runner.xcodeproj/project.pbxproj
- pubspec.lock
- pubspec.yaml
After wasting some time to work on creating an extendable FAB I noticed that there are quite a lot of libraries for this already available, so I just picked one and used it. 
We can easily change this later if we don't like it.
---
> Speed-dial FAB for send and receive

- integration_test/dashboard_test.dart
- lib/balance.dart
- lib/dashboard.dart
- lib/main.dart
- lib/mocks/payment_history.dart
- lib/models/amount.model.dart
- lib/models/balance_model.dart
- lib/models/payment.model.dart
- lib/payment_history_list_item.dart
- pubspec.lock
- pubspec.yaml
Add a simple payment list filled with generated dummy values.
There is some room for finetuning for a better UX here, I tried to keep it simple.
--- 
Following is a list of improvements that can be done in follow-ups. 
Some of these little improvements are time-sinks so I stopped improving things for now :)
- Display the `+` sign as well (not just `-`)
- Keep the balance pinned to the top when scrolling (could also keep the service-tiles selector, but maybe shrink it upon scrolling)
- Improve the look and feel of the list items - It would be cool to also have a meaningful subtitle (e.g. the date/time when this happened...)
> Payment list

- lib/balance.dart
- lib/cfd_trading/cfd_offer.dart
- lib/cfd_trading/cfd_order_confirmation.dart
- lib/cfd_trading/cfd_order_detail.dart
- lib/cfd_trading/cfd_overview.dart
- lib/models/amount.model.dart
- lib/payment_history_list_item.dart
> Fix screen overflows, refactor `Amount` display

- CHANGELOG.md
Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/itchysats/10101/actions/runs/3426187585.
I've bumped the versions in the manifest files in this commit: 64eda1f0ec26732ad25ff2750fb7b767f8536050.
> Release version 0.1.0

- Makefile
I've noticed that I haven't been running tests as often as I should have -
hopefully this will make it a bit easier.
> chore: Add `make test` for running tests

- lib/cfd_trading/cfd_order_detail.dart
> Add confirmation to cfd settlement

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/api.rs
- rust/src/disk.rs
- rust/src/hex_utils.rs
- rust/src/lib.rs
- rust/src/lightning.rs
- rust/src/wallet.rs
- Use bdk-ldk crate to create a BdkLdkWallet
- setup lightning node
- start lightning node networking
- add open_channel API
So far the sync on lightning happens periodically, but there's not much to see when there are no
peers connected.
You can also see outputs in `logs.txt` as well.
TODO: Handle ldk events
Co-authored-by: Richard Holzeis <richard@holzeis.me>
> Add initial LDK integration

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/hex_utils.rs
- rust/src/lightning.rs
Heavily influenced by bdk_ldk_sample
> Implement ldk_event_handler

- lib/main.dart
- lib/wallet/open_channel.dart
- lib/wallet/wallet_dashboard.dart
> Add `Open Channel` screen

- lib/main.dart
- lib/models/payment.model.dart
- lib/wallet/payment_history_list_item.dart
- lib/wallet/wallet.dart
- lib/wallet/wallet_bitcoin.dart
- lib/wallet/wallet_dashboard.dart
- lib/wallet/wallet_lightning.dart
Includes the changes as proposed in the review remarks given here https://github.com/itchysats/10101/pull/146
> chore: Minor wallet refactoring

- rust/src/logger.rs
Adding a vistor implementation taken from https://burgers.io/custom-logging-in-rust-using-tracing.
@klochowicz I wasn't able to enable the rust logs, so I enabled the dart logs and noticed that the piped log messages from rust only contained the field names but not the values. So I followed the blog post mentioned above to add the values.
> fix: Add values to log messages

- lib/main.dart
- lib/wallet/open_channel.dart
- maker/src/main.rs
- rust/src/api.rs
- rust/src/lightning.rs
- rust/src/wallet.rs
see fb629ef63f56ac498a03cef6fb8634cfc32d02c4
> Open channel

- Cargo.lock
- Cargo.toml
- rust/src/lightning.rs
The fork has support for adding/removing of custom output needed for DLCs to work
> feat: Use our rust-lightning fork

- lib/main.dart
- lib/wallet/payment_history_list_item.dart
- rust/src/api.rs
- sort by newest tx first
- negate money which left the wallet
- use sexy icons
> Minor tx history changes

- rust/src/disk.rs
These logs are  by default stored in `logs.txt`, which makes it hard to debug
during program execution due to lack of surrounding context - enabling them
in tracing makes it easier to spot problems.
Add a custom target `ldk`, so that they can be disabled easily if they become a nuisance.
Note: Unfortunately, rust-lightning is tailored to work with `log` crate instead of
`tracing`, and it's not trivial.
Whilst it can be integrated, it can be a time-sink. Meanwhile, this commit should be
sufficient for debugging purposes.
> feat: Integrate LDK logs into tracing

- .github/workflows/ci.yml
- Cargo.lock
- Makefile
- maker/Cargo.toml
- maker/src/lib.rs
- maker/src/main.rs
- maker/src/routes.rs
- Start Rocket with a simple GET call to get the latest offers
> Add get offers HTTP API to maker

- lib/cfd_trading/cfd_order_confirmation.dart
- lib/models/order.dart
- rust/src/api.rs
- rust/src/lightning.rs
- rust/src/wallet.rs
As far as I can tell, the taker is able to open a CFD.
> Allow taker to open a CFD

- Cargo.lock
- maker/Cargo.toml
- maker/src/main.rs
- maker/src/routes.rs
- rust/src/lightning.rs
- rust/src/wallet.rs
Useful for resetting the state when testing locally.
> Allow maker to force-close first channel

- Cargo.lock
- Cargo.toml
- lib/cfd_trading/cfd_order_detail.dart
- rust/src/api.rs
- rust/src/lightning.rs
- rust/src/wallet.rs
Fixes #183.
Amounts currently hard-coded.
> Allow maker to settle a CFD via the UI

- rust/src/lightning.rs
While not recommended in production, we allow 0-conf channels. To do so we need to manually confirm all channel requests.
resolves #206
> feat: allow 0-conf channels

- docs/ppp/iteration-5-16112022.md
already published, sicne we are already late. But happy to update in case you have any feedback / objections.
https://makers.bolt.fun/story/ppps-week-5-10101--397
> docs: fifth lol ppp

- Cargo.lock
- Cargo.toml
- lib/wallet/open_channel.dart
- maker/src/main.rs
- maker/src/routes.rs
- rust/src/api.rs
- rust/src/lightning.rs
- rust/src/wallet.rs
resolves #199
The part where we "ignore" the makers tx for funding (on bitcoin history and balance) is not implemented yet. 
I am planning to work on this in a follow-up PR on top because it is a  bit tricky to get right.
Note: Still testing if it works :)
> Maker to send funds on open channel

- lib/main.dart
- lib/mocks/payment_history.dart
- lib/models/payment.model.dart
- lib/payment_history_change_notifier.dart
- lib/wallet/payment_history_list_item.dart
- lib/wallet/wallet_lightning.dart
- rust/src/api.rs
- rust/src/lightning.rs
- rust/src/wallet.rs
Resolves #165 
Note: 
* What is missing is the overview of the actual CFDs. I think we don't have this data yet.
* We cannot know easily which transaction opened the channel. For that we will need to store some additional data somewhere.
> Lightning payment history

- .dockerignore
- .github/workflows/publish_docker.yml
- Dockerfile
- README.md
Resolves #205 
Note: the binary in the container is throwing an error at the moment.
```
Error: Cannot assign requested address (os error 99)
```
This might be a problem of how we listen for rocket. I'll create a ticket for that.
> feat: publish maker docker on each push to master

- maker/src/main.rs
> chore: make maker listen on `0.0.0.0:8000`

- Cargo.lock
- Dockerfile
- maker/Cargo.toml
- maker/src/cli.rs
- maker/src/lib.rs
- maker/src/main.rs
- rust/src/api.rs
- rust/src/lightning.rs
- rust/src/wallet.rs
Once this is in we can do #228 
Resolves #217
> Add maker cli

- Dockerfile
> fix: use correct target binary

- lib/main.dart
- lib/models/payment.model.dart
- lib/wallet/payment_history_list_item.dart
- lib/wallet/receive_on_chain.dart
- lib/wallet/send_on_chain.dart
- lib/wallet/wallet_bitcoin.dart
- lib/wallet/wallet_dashboard.dart
- rust/src/api.rs
Fixes #114.
https://user-images.githubusercontent.com/9418575/202347714-cb78e967-8b16-46dd-a772-fff67a1a5aee.mp4
> Implement functionality to send bitcoin on-chain

- lib/balance.dart
- lib/cfd_trading/cfd_offer.dart
- lib/cfd_trading/cfd_order_confirmation.dart
- lib/cfd_trading/cfd_order_detail.dart
- lib/cfd_trading/cfd_overview.dart
- lib/models/amount.model.dart
- lib/utilities/tto_table.dart
- lib/wallet/payment_history_list_item.dart
The table formatting bugged me a bit so I unified it.
I've also unified amounts to be sats everywhere
Note: The ordering in the tables is still a bit off and overall can need a bit more love.
> format flutter tables

- lib/wallet/send.dart
- maker/src/main.rs
- maker/src/routes.rs
- rust/src/api.rs
- rust/src/lightning.rs
- rust/src/wallet.rs
In order to test, I have added some basic API to generate an invoice on the maker side.
TODO(follow-up): Improve the invoice generation API and hook it up into 10101.
> feat: Support paying lightning invoices

- lib/cfd_trading/cfd_offer.dart
- lib/cfd_trading/cfd_order_confirmation.dart
- lib/cfd_trading/cfd_order_detail.dart
- lib/cfd_trading/cfd_overview.dart
- lib/cfd_trading/cfd_trading_change_notifier.dart
- lib/models/amount.model.dart
- lib/models/order.dart
- rust/migrations/202211170900_create_cfd_table.sql
- rust/sqlx-data.json
- rust/src/api.rs
- rust/src/calc.rs
- rust/src/cfd.rs
- rust/src/db.rs
- rust/src/wallet.rs
Replaces mocked data with actual calculated data.
Please have a close eye on the calculations. E.g. I did not include any fees in the online calculation. Not sure if everything is correct. It looked good to me, though.
Side note, we should start writing tests again after the tournament. 😅
> Add calculations

- lib/cfd_trading/cfd_offer.dart
- lib/cfd_trading/cfd_order_confirmation.dart
- lib/cfd_trading/validation_error.dart
- lib/main.dart
Fixes #200.
Insufficient funds:
https://user-images.githubusercontent.com/9418575/202710349-cded625d-0ac5-4583-8ebd-c101583659cf.mp4
No open channel:
https://user-images.githubusercontent.com/9418575/202710568-21dcbf5d-d2c6-496d-93e8-46435e423d68.mp4
> Check channel state before opening CFD 

- maker/src/main.rs
- maker/src/routes.rs
- rust/src/cfd.rs
- rust/src/offer.rs
- rust/src/wallet.rs
Remove some arbitrary constraints, such as:
- add up the balance in all open channels
- when opening CFD, look at first open channel with *maker*
> Support more than one channel

- docs/ppp/iteration-6-22112022.md
> Sixth lol ppp

- lib/models/amount.model.dart
- lib/models/payment.model.dart
- lib/wallet/payment_history_list_item.dart
- lib/wallet/wallet_dashboard.dart
> chore: format payment history

- lib/main.dart
- lib/wallet/receive.dart
- maker/src/routes.rs
- rust/src/api.rs
- rust/src/lightning.rs
- rust/src/wallet.rs
- align the API to allow passing custom description when creating invoice
- Add a Flutter widget that allows creating an invoice. You can specify amount,
expiry time, and add a custom description.
It generates a QR code and allows you to copy invoice to clipboard.
> feat: Generate lightning invoices

- Cargo.lock
- Cargo.toml
- lib/cfd_trading/cfd_order_confirmation.dart
- lib/cfd_trading/cfd_order_detail.dart
- lib/cfd_trading/cfd_overview.dart
- lib/cfd_trading/cfd_trading_change_notifier.dart
- rust/migrations/20221121154700_add_close_price_to_cfd_table.sql
- rust/sqlx-data.json
- rust/src/api.rs
- rust/src/cfd.rs
- rust/src/db.rs
This PR calculates the settlement amounts and updates the cfd state in the database. Still not a 100% sure if all the calculations are correct, but at least the maker + taker amount add up to the total margin - so that the settlement goes through 🥳 
resolves #219
> Calculate settlement amounts

- lib/wallet/send.dart
- lib/wallet/send_on_chain.dart
We are within a `SafeArea` and don't need a margin here, these buttons look different than in other child screens. Removing margin to align.
> Align button margins

- lib/cfd_trading/cfd_order_detail.dart
> Fix margin on cfd order details

- lib/cfd_trading/cfd_trading.dart
- lib/main.dart
- lib/menu.dart
- lib/models/service_model.dart
- lib/service_placeholders.dart
- lib/wallet/service_card.dart
- lib/wallet/wallet_dashboard.dart
This fills up empty space and shows the vision better.
> Showcase more services

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- ios/Podfile.lock
- ios/Runner/Info.plist
- lib/cfd_trading/cfd_trading.dart
- lib/cfd_trading/market.dart
- pubspec.lock
- pubspec.yaml
Embed a TradingView bitmex XBTUSD widget inside a webview.
Note: it works on Android/iOS. Desktop platforms get a placeholder that the
functionality is not supported yet.
I've recorded in landscape, as it's much nicer for viewing charts like that 😁
https://user-images.githubusercontent.com/8319440/203267520-dd5b8835-12e2-4ca1-8aa9-579b5e8f081a.mov
> feat: Add market view

- lib/wallet/open_channel.dart
Still a lot of text, but it's much better organized in my point of view. The text could probably use some more love though.
resolves #287
> chore: Improve open channel view

- lib/cfd_trading/cfd_offer.dart
- lib/cfd_trading/cfd_order_confirmation.dart
- lib/cfd_trading/cfd_order_detail.dart
- lib/utilities/tto_table.dart
> chore: Improve table layout and styling

- lib/main.dart
> Higher frequency for sync calls with the rust backend

- lib/wallet/open_channel.dart
https://user-images.githubusercontent.com/224613/203450889-db28fc38-2997-46a4-8ea6-2a2adf14170a.mov
> fix: make open channel scrollable

- rust/src/lightning.rs
No difference in behaviour, only added more logs for debugging.
converted some `println` into `tracing` and added more logs for events we are not handling yet.
> chore: Add more logging around handling lightning events

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/Info.plist
- linux/CMakeLists.txt
- macos/Runner/Configs/AppInfo.xcconfig
- windows/runner/Runner.rc
Use `10101` as the product name consistently, including copyright notices.
I've also set `itchysats` as the company.
> chore: Fix product strings

- maker/src/main.rs
- maker/src/routes.rs
Fixes the issue with spread not always being updated properly.
This is more idiomatic way of updating the value from another thread,
e.g. provides more info about what's being updated where.
Proof that it works below: 
```sh
➜  10101 git:(use-a-watch-channel-instead-of-atomic-state) ✗ curl -X GET "http://localhost:8000/api/spread"
0.015%
➜  10101 git:(use-a-watch-channel-instead-of-atomic-state) ✗ curl -X PUT "http://localhost:8000/api/spread"
➜  10101 git:(use-a-watch-channel-instead-of-atomic-state) ✗ curl -X GET "http://localhost:8000/api/offer"                                                                                                                                                                                                         <<< …
```
> Use a watch channel instead of atomic for SpreadPrice

- maker/src/bitmex.rs
After subscribing to the topic `instrument:XBTUSD` on BitMEX, we immediately get the entire table of current values. This meant that we would succeed in initially setting all the `Quote` data.
But every subsequent update that we get via the websocket is not guaranteed to contain all of `bidPrice`, `askPrice` and `markPrice`. Consequently we were almost always failing to deserialise the table updates, because all of those fields were mandatory.
> Handle fields in BitMEX table update separately

- lib/cfd_trading/cfd_offer.dart
> chore: add currency to the bitmex prices

- lib/cfd_trading/cfd_offer.dart
- lib/cfd_trading/cfd_order_confirmation.dart
- lib/cfd_trading/cfd_order_detail.dart
- lib/cfd_trading/validation_error.dart
- lib/wallet/receive_on_chain.dart
> fix: Improve warnings displayed when opening a CFD

- docs/ppp/pitch-23112022.md
Ignore formatting.
I wrote this in bolt.fun and copied it over to save time with formatting later on.
resolves #257
> doc: add pitch doc to be released on bolt.fun

- maker/src/main.rs
- maker/src/routes.rs
- rust/src/lightning.rs
- rust/src/wallet.rs
Resolves #340 
added info about connected peers and high-level channel info (how many are open & how many are usable)
> Expose more stats in maker's API

- maker/src/logger.rs
- rust/src/lightning.rs
- rust/src/logger.rs
- don't use a Filter (no need)
- handle missing events
- reduce log spam
> A bunch of improvements for ldk events handling

- lib/wallet/seed.dart
Use the same one as provided in bitcoin.design template
> chore: Rephrase seed backup text

- maker/src/main.rs
- maker/src/routes.rs
- rust/src/lightning.rs
- rust/src/wallet.rs
to force close call: 
```
curl -X POST http://localhost:8000/api/channel/close/0244946473b7926c427be70925e8e99cafc3ea76dffe708e6cba8896576cf0b14d\?force\=true
```
to collab close call
```
curl -X POST http://localhost:8000/api/channel/close/0244946473b7926c427be70925e8e99cafc3ea76dffe708e6cba8896576cf0b14d
```
> feat: allow collab close channel through api

- Cargo.lock
- maker/Cargo.toml
- maker/src/routes.rs
making this thing a bit more useful
> feat: return channel list in api

- lib/cfd_trading/cfd_offer.dart
- lib/cfd_trading/cfd_order_confirmation.dart
- lib/cfd_trading/cfd_trading_change_notifier.dart
Note: @luckysori also fixed this on `fix/responsive-offer-lucas` - if the solution is equivalent we can close this PR as well :)
> Fix value refresh on price change

- CHANGELOG.md
It's hard to capture everything we did since release `0.1.0` - a lot has happened.
I tried to summarize what we did on a somewhat high level, focussing on the big feature and what the user can see. 
Suggestions to add something or word things different welcome!
@holzeis I'm assigning you to this PR now, because you will likely be the one merging it later :)
> Prepare changelog update for `0.2.0` release

- lib/wallet/open_channel.dart
- rust/src/api.rs
- rust/src/lightning.rs
> Add more error info

- README.md
Since I ran into this problem I thought I'll capture this in the readme :)
> Extend readme to capture `NETWORK` variable

- lib/cfd_trading/cfd_order_confirmation.dart
- lib/cfd_trading/cfd_order_detail.dart
- lib/cfd_trading/cfd_trading.dart
- lib/main.dart
- lib/menu.dart
- lib/models/service_model.dart
- lib/wallet/wallet.dart
- lib/wallet/wallet_dashboard.dart
- lib/wallet/wallet_lightning.dart
- cfd --> trading
- exchange --> combined in trading
- betting --> removed
- DCA --> added
Services updated
Menu updated
`My CFD` --> `Positions`
> chore: rename services a bit

- CHANGELOG.md
- pubspec.yaml
Hi @luckysori!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/itchysats/10101/actions/runs/3545890190.
I've bumped the versions in the manifest files in this commit: 6653d833d7a455903a3a54eb22526cb9c7ec5ee1.
> Release version 0.2.1

- rust/src/lightning.rs
We don't know exaclty why it was not working before, but this works :)
resolves #313
> fix: make ln payment work

- lib/main.dart
- maker/src/main.rs
- rust/src/api.rs
- rust/src/wallet.rs
> sync-optimizations

- rust/src/wallet.rs
If the user specifies a send amount that _equals_ their total funds, we call `drain_to` instead of `add_recipient`. Otherwise it fails because we cannot pay for transaction fees.
> Let the taker's Bitcoin wallet be drained

- lib/cfd_trading/cfd_order_confirmation.dart
- lib/cfd_trading/cfd_order_detail.dart
- lib/utilities/async_button.dart
- lib/utilities/submit_button.dart
- lib/wallet/open_channel.dart
- lib/wallet/send.dart
- lib/wallet/send_on_chain.dart
resolves https://github.com/itchysats/10101/issues/389
Button widget that takes a `dynamic` arbitrary function callback and calls it in an async fashion.
On success evaluation of the future we show a success snackbar message. On failure evaluation of the future we show a failure snackbar.
Note:
Dart does not allow arbitrary function arguments as part of type arguments, i.e. we cannot define a function that "takes any amount of dynamic arguments". To allow some level of flexibility we allow functions with 0, 1, 2 and 3 parameters where the parameters are passed as separate optional arguments.
---
Will be done in follow up:
-  Make the button larger (We should handle that through the Theme and not set anything specific in `AsyncButton`).
> Introduce reusable `SubmitButton`

- lib/main.dart
- rust/src/api.rs
- rust/src/connection.rs
- rust/src/disk.rs
- rust/src/lib.rs
- rust/src/lightning.rs
- rust/src/wallet.rs
Both actions are blocking, this will free up a thread.
> chore: Combine run ldk and connect into a single thread

- lib/main.dart
Remaining part of https://github.com/itchysats/10101/issues/389
This changes the `ElevatedButton` (that we use as submit button) throughout the application.
Increase minimum size to `width: 100 height: 50` and font size to `16`.
> Larger `ElevatedButton`

- ios/Flutter/AppFrameworkInfo.plist
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- ios/Runner/Base.lproj/Main.storyboard
- ios/Runner/RunnerProfile.entitlements
- linux/CMakeLists.txt
- macos/Runner/Configs/AppInfo.xcconfig
- macos/Runner/Release.entitlements
- windows/runner/Runner.rc
note: we are going for the app id finance.10101.app which is backwards the domain: 10101.finance.
needed for #409 
Formatting changes are automatically done by xcode
> chore: prepare app to be built for ios

- rust/src/api.rs
> Set CFD expiry to 30 days

- lib/wallet/send.dart
- rust/src/api.rs
> feat: Add invoice details

- rust/src/lightning.rs
- rust/src/wallet.rs
Match on all errors, and make it clear that the error is from the maker.
> chore: Improve error message if maker is unable to open channel

- lib/main.dart
- lib/wallet/wallet_bitcoin.dart
- lib/wallet/wallet_dashboard.dart
- lib/wallet/wallet_lightning.dart
Small feature on the way :)
https://user-images.githubusercontent.com/224613/204672346-f4b00e59-aa54-4a0a-bf97-0f6d707ee407.mov
> feat: pull down to sync

- rust/Cargo.toml
- rust/src/lightning.rs
- rust/src/logger.rs
- rust/src/wallet.rs
Just like for ItchySats, use sled for storing utxos.
> feat: Persist bdk UTXOs in a sled database

- docs/ppp/iteration-7-30112022.md
I think we should publish one for this last week :)
> doc: add ppp 7

- lib/wallet/open_channel.dart
Otherwise the button never spins! You were right @da-kami.
> Await for channel to be open

- lib/wallet/fund_wallet_on_chain.dart
I guess "do it later" means going back to the home screen?
> fix: Navigate back to home on do it later

- android/app/build.gradle
This is required for an android build after integrating the launcher pub.
> fix: Increase sdk version and enable multidex

- rust/src/wallet.rs
That's a bit cleaner in the directory
> chore: store wallet stuff inside a sub-dir

- lib/wallet/wallet_lightning.dart
Not the nicest fix, but small and functional. Once we have a better depiction of the channel on the frontend we should adapt that.
resolves #465
> fix: Hide close channel on empty lightning balance

- lib/cfd_trading/cfd_offer.dart
- lib/utilities/dropdown.dart
resolves https://github.com/itchysats/10101/issues/405
Took me a while to get this together. The usual "tiny details make the difference" UI challenges :)
I first experimented with changing the screen and moving the `FormTextField` in a separate row. But we run into space problems that are difficult to solve then. 
We could change the *overall* table font size to gain a bit more space, then it might be possible. But I felt it was not worth investing more time into this (it leaks through multiple screens then), so I opted for keeping the three fields in 
I also looked into adding a modal drawer that opens from the bottom where the user is guided to enter the values. But that does not make it much better, because it's hard to see the effect of entering the values then.
Note: I opted for a …
> Quantity text field, validation and more leverage choices

- ios/Podfile.lock
Not sure what triggered this, and why the file was not changed on the machine that introduced that change, but since I keep seeing this I created a PR :)
I guess this is relevant for other mac users
> Podfile change

- rust/src/wallet.rs
fixes https://github.com/itchysats/10101/issues/488
Deals with the possibility of previously failed channel opens that have an entry in the transactions to be ignored. It's not trivial to associate the funding-txid of the maker with the actual channel-open-txid where the funding was used in our current flow. This is hacky as fuck, but the whole solution of the maker funding the taker is hacky as fuck, so 🤷‍
> More resilient ignore logic

- lib/menu.dart
> fix: close sidebar on click

- lib/cfd_trading/cfd_order_detail.dart
- lib/main.dart
> chore: Add outline button theme

- lib/cfd_trading/cfd_offer.dart
- lib/cfd_trading/cfd_order_detail.dart
- lib/wallet/wallet_lightning.dart
No channel 
Channel needs confirmation
lightning wallet, no channel
can't close position if channel is not available
resolves https://github.com/itchysats/10101/issues/485
resolves https://github.com/itchysats/10101/issues/428
> Disable channel actions

- Cargo.toml
see PR here: https://github.com/itchysats/bdk-ldk/pull/8
> fix: re-org bug was fixed upstream

- CHANGELOG.md
- pubspec.yaml
Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/itchysats/10101/actions/runs/3600673207.
I've bumped the versions in the manifest files in this commit: 1ee6f4b1b6209cd8e7a554fb14c86d170ee81cae.
> Release version 0.3.0

- CHANGELOG.md
- pubspec.yaml
Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/itchysats/10101/actions/runs/3601736476.
I've bumped the versions in the manifest files in this commit: eff120d459e0334f0abd4b5856005d213c16d020.
> Release version 0.3.1

- lib/main.dart
- lib/menu.dart
- lib/settings.dart
- rust/src/api.rs
I found myself wanting to know what id I have so that I can look it up on the maker side.
Design needs some love, but it's functional:
> feat: show some useful information in settings screen

- lib/main.dart
- lib/wallet/lightning_tx_detail.dart
- rust/migrations/20221205002340_add_expiry_timestamp_to_payment_info.sql
- rust/sqlx-data.json
- rust/src/db.rs
- rust/src/lightning.rs
- rust/src/wallet.rs
See commit details for more details.
screenshots
payment details:
> Clear expired lightning payments

- lib/wallet/receive.dart
> fix: Accept text input for invoice description

- ios/Podfile.lock
- lib/app_info_change_notifier.dart
- lib/main.dart
- lib/settings.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
> Version and network display in settings and logs

- lib/wallet/open_channel.dart
> fix: Set initial value to takerChannelAmount

- CHANGELOG.md
- pubspec.yaml
Hi @da-kami!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/itchysats/10101/actions/runs/3635440547.
I've bumped the versions in the manifest files in this commit: 4569a4e07612da1d06c34c355a3d89740567150d.
> Release version 0.3.2

- rust/src/db.rs
- rust/src/lightning.rs
SqlitePool and invoice payer were using `State` which we wrongly assumed needed
a mutex.
> chore: Remove unneeded mutexes
