Makefile, lib/off_topic_code.dart
Unfortunately, I couldn't get dprint working for flutter.
As a stopgap, here's a simple Makefile that can be used to call both formatters
at once.
=> chore: Add a simple Makefile to encapsulate formatting

Makefile, README.md
Expand Makefile to encapsulate all the convoluted commands needed.
Update README.md to mention the Makefile
=> Provide instructions for building on all targets, including mobile

.github/dependabot.yml
Start off with weekly updates so it's not too annoying.
=> chore(deps): Enable dependabot for flutter packages

.github/workflows/ci.yml, .github/workflows/flutter_android_test.yml
So far the test doesn't do anything useful besides what was already in the
example found in rust-flutter-bridge repo; it serves as a basis to see that we
end-to-end test the application on Android.
=> chore(ci): Build and test the whole app on Android

.github/workflows/ci.yml, bors.toml
Bors keeps timing out, docs say using some accumulated job is more
reliable (this was the case with itchysats, although we had many matrix
builds there)
=> fix(ci): Use an accumulated job for bors purposes

Makefile, README.md
Android simulator needs a different rust target (x86_64).
Mention the new variants in the README.
=> fix: Provide separate make targets for Android sim and native build

README.md
For people not familiar with either, point them to the relevant guides instead
of copying them.
=> docs: Add links to Flutter guide and Rustup

.github/workflows/ci.yml
Include CI workflows in detecting the `changes`, otherwise we risk merging a
faultly workflow change.
The simplest way is to just rerun both `rust` and `flutter` changes whenever a
workflow has changed.
=> chore(ci): Don't skip CI jobs when workflow

docs/research/wallet-comparison.md
This is an attempt to get a deeper understanding of non-/semi-custodial wallet setups out there and a feature comparison of the wallets implementing them. 
This will help to position 10101 in the market, define our preferred setup and compare our solution to existing solutions out there.
=> Wallet comparison

lib/balance.dart, lib/cfd_trading.dart, lib/dashboard.dart, lib/main.dart, lib/models/service.model.dart, lib/service_card.dart
Includes navigation to CFD Trading screen, but we need more complex routing and should plug in a routing library as recommended here: https://docs.flutter.dev/development/ui/navigation#using-the-navigator
I will work on introducing [go_router routing library](https://pub.dev/packages/go_router) so we can depict the routing between the wallet and the service screens. 
Note on naming: I don't particularly like the name `service` for trading/bets (...) - I thought about different names (e.g. `feature` or `in-app-...?`) but did not come up with anything satisfying so I just went with `service` for now.
=> Add service selector to dashboard

lib/cfd_trading.dart, lib/dashboard.dart, lib/main.dart, lib/mocks.dart, lib/seed.dart, pubspec.lock, pubspec.yaml
This allows us to specify sibling routes (e.g. wallet screen to cfd-trading screen) and parent-child (descending) routes (e.g. wallet screen to wallet-backup seed screen).
=> Add go router to allow more complex routing

lib/main.dart, rust/src/api.rs, rust/src/lib.rs, rust/src/logger.rs, rust/src/wallet.rs
Provide some basic API to stream Rust logs to Flutter and stream existing logs
instead of using `println!` macro.
TODO: Use `tracing` infrastructure to stream the logs, instead of handcrafted function
TODO: after adding support for `tracing` and adding a Flutter log package, send
over timestamps, log level etc.
=> feat: Send Rust logs to flutter

Makefile
I noticed that sometimes we can't re-run certain recipes, e.g. iOS compilation:
```
➜  10101 git:(main) ✗ make ios
make: `ios' is up to date.
```
Fix it by introducing a `FORCE` target, as suggested here:
https://stackoverflow.com/questions/26226106/how-can-i-force-make-to-execute-a-recipe-all-the-time
=> fix: Ensure Makefile recipes always re-run

rust/Cargo.lock, rust/Cargo.toml
We will need matching version of rust-bitcoin to integrate bdk and ldk
=> chore(deps): Bump bdk to 0.24

lib/seed.dart
In an effort to get a better hang of how flutter works and make sure our screen layout is at least somewhat responsive (the wireframes were for iPhone SE...) I worked on the layout of the seed screen.
I will see to apply my learnings to other detail / confirmation screens next :)
This is how it looks on different devices now:
---
Note: 
I went one step further and used a FAB for confirmation as well using this code:
```dart
floatingActionButton: FloatingActionButton.extended(
backgroundColor: checked ? Theme.of(context).colorScheme.primary : Colors.grey[300],
foregroundColor: checked ? Colors.black : Colors.grey[600],
onPressed: checked
? () {
final seedBackupModel = context.read<SeedBackupModel>();
seedBackupModel.update();
context.go('/');
}
: null,
label: const Text('Done'))
```
But …
=> Seed page layout fixes

lib/main.dart, rust/Cargo.lock, rust/Cargo.toml, rust/src/logger.rs, rust/src/wallet.rs
This allows us to see bdk etc logs in our app.
The logs are sent to Dart as well.
note: temporarily disable displaying debug logs from Rust in flutter (to not
double up, esp. when tracing provides much nicer views)
=> Add tracing to see Rust logs

lib/main.dart, pubspec.lock, pubspec.yaml, rust/src/api.rs, rust/src/wallet.rs
According to the docs, Application Support directory is supported on all platforms.
This should allow us to store wallet-related files on disk.
=> feat: Path Application Support directory from Flutter

lib/main.dart, rust/src/logger.rs
- fix a problem (potential multiple inits of tracing)
- address @holzeis comment from previous review (reenable Flutter debug logs)
- only send logs to Dart in release mode (we don't need them in debug, as we see them on stdout)
=> Rust log improvements

.github/workflows/ci.yml, rust/src/wallet.rs
We started adding some unit tests in the Rust library, so they should be run on
the CI.
=> chore: Add cargo test job to CI

rust/src/wallet.rs
Only try to create the missing directory if it's not there already.
=> fix: Do not error if the seed path already exists

rust/src/api.rs, rust/src/lightning.rs, rust/src/wallet.rs
Store the `data_dir` inside `LightningSystem` so that API can be simpler.
=> chore: Remove `data_dir` argument

rust/src/api.rs, rust/src/lightning.rs, rust/src/wallet.rs
Without this, we are susceptible to a race condition (we need to *hope* that bdk
init will happen before we start other tasks depending on it). If we explicitly
wait for init first, we don't have such a problem.
Add `Clone` trait implementation to Wallet, so that we don't need to hold the mutex to the
wallet when passing some of its data around.
Note: cloning is pretty cheap here, because we're cloning only a bunch of Arc
pointers, not the underlying wallet data.
This makes the API more discoverable, allowing for the usage
`wallet.run_ldk(port)`.
=> chore: Split initialisation and running of LDK

lib/main.dart, lib/mocks/payment_history.dart, lib/models/payment.model.dart, lib/payment_history_change_notifier.dart, lib/wallet/payment_history_list_item.dart, lib/wallet/wallet_bitcoin.dart, lib/wallet/wallet_dashboard.dart, rust/src/api.rs, rust/src/wallet.rs
first part of https://github.com/itchysats/10101/issues/165
Given that this is independent of the Lightning payments (to some extent), it would be great if we can merge this already :)
--- 
Bitcoin history screenshots:
=> Bitcoin payment history instead of mock data

rust/src/lightning.rs
Having a subdirectory will make our `seed` file stand out more
(and all LDK stuff will be together).
=> chore: Put LDK-related data into $DATA_DIR/ldk

maker/src/main.rs, rust/src/lightning.rs
Ran into panic ealier today and was able to fix issue only after this change.
It's easier to debug code if it returns a result than panics.
I left out the ones inside async tasks, as they're not as trivial to remove.
=> chore: Remove unneeded unwrap() calls

Cargo.lock, lib/cfd_trading/cfd_offer.dart, lib/cfd_trading/cfd_offer_change_notifier.dart, lib/main.dart, maker/Cargo.toml, maker/src/bitmex.rs, maker/src/lib.rs, maker/src/main.rs, maker/src/routes.rs, rust/Cargo.toml, rust/src/api.rs, rust/src/lib.rs, rust/src/offer.rs
@bonomat @da-kami Please check the spread calculation on the long and short offers. I tried to align with the logic I found in the maker automation, but I don't think I got it completely right.
- subscribes to the bitmex api for btxusd prices using the instrument target (as this is including bid, ask and index price in one message)
- skipped ethusd for now, as it would only introduce additional complexities which we don't need now.
- reused the bitmex-stream lib from itchysats
- wires offers to the cfd offer screen through periodical rust taker api calls.
- hide material app until ready
see commit messages for more details
resolves #106
=> Fetch bid ask index price from bitmex

lib/wallet/open_channel.dart, rust/src/api.rs, rust/src/wallet.rs
Pass in the hard-coded values to flutter. Expose them in the API so that they
can be displayed.
=> chore: Do not specify maker peer info manually

.github/workflows/ci.yml
Bors started acting up a bit, and I suspect that this might be the reason.
=> fix: Add missing output in the CI job detecting changes

Cargo.lock, lib/main.dart, maker/src/main.rs, rust/Cargo.toml, rust/src/api.rs, rust/src/db.rs, rust/src/lib.rs, rust/src/wallet.rs
I've used sqlx purely as we are familiar with it already. Otherwise, it's a bit of a pain
to use an async database here - a sync one would be much easier (due to frb
async boilerplate and runtime cost).
Database is managed for the lifetime of the app by the `ten_ten_one` library,
after being initialised with `db::init_db()` call.
Database in empty for now, but initialising and acquiring a connection works for
both maker and taker.
Note: There's no need to manually close connections to the DB, because we are
only storing a ConnectionPool, and the connections are closed with RAII when
they get out scope.
=> feat: Add persistent SQLite database

lib/cfd_trading/cfd_offer.dart
We currently don't support ETHUSD, hence removing the option for now,
=> fix: only allow btc usd as traiding pair

.github/workflows/ci.yml
We're not using this job when deriving bors status, so we can avoid running it.
Hopefully this should make other job runners wait shorter.
=> chore: Do not run Android integration tests on bors

Cargo.lock, Cargo.toml, rust/src/wallet.rs
Reduced the number of unwraps happening inside the downstream library and addressed a TODO
=> chore: Bump bdk-ldk lib for improved error handling

Cargo.lock, rust/Cargo.toml, rust/src/wallet.rs
Due to the automated trait implementation, the wallet tried to open the database
in "Regtest" instead of "regtest" directory :|
I should have hand-crafted this in the first place, as @bonomat suggested 😅
=> fix: Database directory on Linux not working

rust/src/wallet.rs
Sending HTTP requests and awaiting response without a timeout is needlessly risky.
=> fix: Add a timeout to reqwest client

lib/main.dart
The wallet returns us a transaction detail which includes the sent amount and received amount. To calculate how much we really sent someone else we need to do some math as the `sent` amount includes the whole amount including the one we receive back in the return.
1. subtract the received amoumt
2. subtract the transaction fee
The remaining is the exact amount we sent someone.
=> fix: display correct sent amount

rust/src/lightning.rs
We would like to support 0-conf, but `rust-lightning` immediately closes the channel because of this snippet<sup>[1]</sup>.
The gist of it is:
- `rust-lightning` marks the channel as ready as soon as the fund transaction appears in the mempool.
- It then sees that the funding transaction has 0 confirmations. It interprets this as the transaction being unconfirmed due to a chain reorg, so it closes the channel for safety reasons.
[1]: https://github.com/lightningdevkit/rust-lightning/blob/a4c164979300b403966bc4185a98327ebd61d294/lightning/src/ln/channel.rs#L5575-L5588.
---
We could also modify `rust-lightning`, but that is slightly riskier.
=> Require 1 confirmation when opening channels

rust/src/lightning.rs
This reverts commit 900f883ef615b490d533b6de1cff6546fe92fcbc.
It turns the problem was not with the original change, but with a faulty regtest state.
=> Revert "fix: Require 1 confirmation when opening channels"

Cargo.lock, lib/cfd_trading/cfd_offer.dart, lib/cfd_trading/cfd_order_confirmation.dart, lib/cfd_trading/cfd_order_detail.dart, lib/cfd_trading/cfd_overview.dart, lib/cfd_trading/cfd_trading_change_notifier.dart, lib/cfd_trading/position_selection.dart, lib/main.dart, lib/models/order.dart, rust/Cargo.toml, rust/migrations/202211170900_create_cfd_table.sql, rust/prepare_db.sh, rust/sqlx-data.json, rust/src/api.rs, rust/src/calc.rs, rust/src/cfd.rs, rust/src/db.rs, rust/src/lib.rs, rust/src/wallet.rs
The Cfd model is to be filled with data from the rust backend. We periodically update the list of Cfds by calling the backend which loads the data from the db. We insert/update/delete the Cfd in the database according to user actions (e.g. open cfd inserts a cfd, ...).
We keep an `Order` model that is used before the CFD exists (i.e. before the custom output is added). The Order is not persisted for the duration of the tournament. We don't deal with failed `Order`s yet, but display them as failed Cfds. This is similar to what we did in ItchySats.
=> Introduce CFD model and persist Cfd data

rust/migrations/20221121024641_ignore_maker_funding_tx_table.sql, rust/sqlx-data.json, rust/src/api.rs, rust/src/db.rs, rust/src/wallet.rs
resolves #232
We save the txid of the funding tx and filter it when creating the history.
=> Ignore maker funding transaction in bitcoin tx history

lib/main.dart
It will be nicer to show demo without this annoying banner. We know when we're
running in debug mode.
=> chore: Remove debug banner

lib/wallet/open_channel.dart
Max allowed channel amount on Lightning in sats: 2^24 - 1 = 16777215. However, we need to
divide it by 3 due to maker's configuration, otherwise it will not be accepted.
=> fix: Clamp open channel amount to maker's constraints

integration_test/wallet_test.dart, lib/app_bar_with_balance.dart, lib/balance.dart, lib/cfd_trading/cfd_offer.dart, lib/cfd_trading/cfd_order_detail.dart, lib/cfd_trading/cfd_overview.dart, lib/cfd_trading/cfd_trading.dart, lib/cfd_trading/position_selection.dart, lib/main.dart, lib/menu.dart, lib/utilities/divider.dart, lib/utilities/dropdown.dart, lib/wallet/action_card.dart, lib/wallet/service_card.dart, lib/wallet/wallet.dart, lib/wallet/wallet_bitcoin.dart, lib/wallet/wallet_dashboard.dart, lib/wallet/wallet_lightning.dart
resolves #280
resolves #282
With the later commits the Dashboard changed to:
Note: The color can be changed globally with one line if needed :)
=> App bar and theme and Dashboard improvements

lib/app_bar_with_balance.dart, lib/cfd_trading/cfd_trading.dart, lib/mocks/payment_history.dart, lib/wallet/payment_history_list_item.dart, lib/wallet/wallet_bitcoin.dart, lib/wallet/wallet_dashboard.dart, lib/wallet/wallet_lightning.dart
The cfd trading screen looks a bit off in comparison to the other screens. But I didn't figure out quickly why this is the case. Leaving it as it is for now, since it isn't a priority for the tournament.
resolves #306
=> Fix: balance is not visible on iphone

maker/src/main.rs, maker/src/routes.rs
Exposes an api on the maker to set the spread manually. This is for demo purposes!
update spread like this
```
curl -X PUT http://127.0.0.1:8000/api/spread/0 # sets spread to 0.0
curl -X PUT http://127.0.0.1:8000/api/spread/-30 # sets spread to -0.03
```
get the current spread like this
```
curl http://127.0.0.1:8000/api/spread
```
Note, I am dividing any input by 1000 to simplify the put request, also I opted to use an url parameter instead of the body for convenience reasons.
resolves #275
=> Update maker spread through api

maker/src/routes.rs
We don't need to flip bid/ask. Think about this:
- taker comes and goes long: he gets the ask price
- if we hedge on BitMEX, we get the ask price there as well
- to make a profit, we need to get a better ask price on BitMEX then we give to the taker --> no need to flip bid/ask
=> fix: bid/ask were flipped.

lib/cfd_trading/cfd_overview.dart
The cfd overview was still calculating the pnl with the index price as a closing price.
=> fix: Use bid / ask price as closing price

rust/src/offer.rs
Initially the maker may return an `No quotes found` message as response with status code `NOT_FOUND`. This does not result in an `Err` on the client, but in a response that cannot be deserialized.
=> Catch the case where we return an `HttpApiError` instead of the response

lib/main.dart, lib/wallet/payment_history_list_item.dart
Refactor the switch statement to correctly parse status after data type.
While at there: change the lightning transaction colour slightly to make them
differentiate a bit.
=>  fix: Mark pending lightning transactions as "off-chain"

lib/wallet/receive_on_chain.dart
Just as the receive on-chain, constrain the size of the QR code to 250x250px.
This prevents it from overflowing when width of the app is greater than
height (e.g. in landscape mode on phone or on desktop).
=> fix: Constrain qr code maximum size

lib/wallet/receive.dart, lib/wallet/receive_on_chain.dart
Fixes #285.
We are not embedding the icon in the QR codes because it renders them unusable.
=> Improve receive-bitcoin page

rust/src/api.rs
This fixes the problem when we had opening price, but no closing price.
=> fix: Prevent division by zero

lib/main.dart, lib/wallet/open_channel.dart, maker/src/main.rs, maker/src/routes.rs, rust/src/api.rs, rust/src/lightning.rs, rust/src/wallet.rs
This PR improves the way 10101 is managing connections with the maker by introducing a dedicated connect api.
Among other improvements this PR fixes the following error.
```
flutter: {CfdOrderConfirmation} {build} {Failed to open CFD: Peer for first hop currently disconnected/pending monitor update!} {FfiException(RESULT\_ERROR, Peer for first hop currently disconnected/pending monitor update!, null)} {LogLevel.ERROR} {21 November 2022 02:04:37 PM}
```
- Instead of blocking indefinitely when creating a channel to keep the channel alive, we now connect to the maker upon startup. Before a new thread was kept alive indefinitely everytime a new channel has been created. The thread pool was very limited though resulting into other request not getting processed and blocked!
- Check if the maker …
=> fix: Recover connection after taker or maker disconnect.

lib/wallet/receive.dart, lib/wallet/receive_on_chain.dart
Lightning invoice is too long to be displayed in full and it overflows.
=> fix: Don't display full lightning invoice

lib/main.dart
All anyhow::Result<> going through API are coming up as exceptions, and we need
to be mindful whenever we call Rust api that returns one - we should always
wrap them in a try/catch block.
=> fix: Catch exception during wallet sync

lib/main.dart, maker/src/cli.rs, maker/src/main.rs, maker/src/routes.rs, rust/src/api.rs, rust/src/cfd.rs, rust/src/config.rs, rust/src/lib.rs, rust/src/lightning.rs, rust/src/offer.rs, rust/src/wallet.rs
Revamp configuration to pass NETWORK env variable from command line (both for
taker and maker).
In case it's not set, or it's invalid, it defaults to testnet.
Move all the config values to a dedicated module to clear the code.
For local development, I recommend to set `export NETWORK=regtest` in your
bashrc to preserve previous behaviour.
=> feat: Support testnet

lib/cfd_trading/cfd_trading_change_notifier.dart, lib/wallet/wallet_lightning.dart
This is because of a current limitation of our `rust-lightning` fork which we will fix in the future.
=> Disable Lightning payments if there is an open CFD

lib/main.dart
Lack of maker should not prevent anyone from using the app as a regular
bitcoin/lightning wallet.
Show the splash screen until the wallet is initialised
=> fix: Don't hang on splash screen if maker is unreachable

rust/src/config.rs, rust/src/lightning.rs
Fixes #369.
Interestingly, reverting https://github.com/itchysats/10101/commit/38c09b25c8903e2aeb6831c637493f88e5731ff1 does the trick.
My theory is that the taker wasn't able to pick up the funding transaction because of the missing filter, so the channel would never be considered ready and the short channel ID would never be available when opening a CFD.
=> Fix open CFD functionality

lib/main.dart
I have tested it with the app running, just forgot to add a screenshot (it displays a `-` instead :) )
=> fix: Present sent off-chain payments as negative

Makefile, README.md
Makefile is for devs, so let's make it more convenient.
note: plain `flutter run` still will require a `NETWORK` override
=> chore: Set Makefile to run on regtest by default

rust/src/wallet.rs
Send to address is called from the open channel route and takes quite some time - letting the client timeout for the request and the channel fails to open.
Sync is already running every 10 seconds - so the wallet should anyways be up to date.
Hard to test since it's not reproducible locally, but I think this resolves #388
=> fix: Skip syncing the wallet when sending to address

lib/main.dart, rust/migrations/20221128012310_add_payments.sql, rust/sqlx-data.json, rust/src/db.rs, rust/src/lightning.rs, rust/src/wallet.rs
note: this is just the insert/load API with tests, adding it now to avoid trouble rebasing later (and to spark a conversation whether we should use one or two tables (inbound / outbound payments)
=> Add sqlite support for storing lightning payments

lib/cfd_trading/cfd_order_confirmation.dart
An error is present if `channelError` is not null.
=> Fix condition to disable the submit button if an error is present

CHANGELOG.md, lib/main.dart, lib/wallet/close_channel.dart, lib/wallet/wallet_lightning.dart, rust/src/api.rs, rust/src/lightning.rs
Fixes #373.
For now it defaults to a collaborative closure. Eventually, we might want to let the taker force-close.
https://user-images.githubusercontent.com/9418575/204174964-f09e3854-f911-496a-abfb-24b4a9962530.mp4
=> Allow taker to close channel with 10101 maker

maker/src/main.rs
We split syncing from getting the balance in patch f7e300dbb31fca4f1aadc1504cc711365220909e. This was okay for the taker, who still syncs periodically.
On the other hand, the maker was only calling `get_balance` periodically. Therefore, the UTXO set was no longer being updated.
=> Sync the maker with the blockchain periodically

.github/workflows/ci.yml
Bors got overwhelmed by these integration tests again.
Only run them on individual PRs instead to make bors happy.
=> chore(ci): Don't run integration tests on bors

lib/cfd_trading/cfd_trading.dart, lib/main.dart, lib/service_placeholders.dart, lib/wallet/wallet.dart, lib/wallet/wallet_bitcoin.dart, lib/wallet/wallet_dashboard.dart, lib/wallet/wallet_lightning.dart
Notes on setting `SystemUiOverlayStyle`:
I wanted to achieve that for the main screens we would use `SystemUiOverlayStyle.dark` and for the child screens (with blue app-bar on top) we would use `SystemUiOverlayStyle.light`, but unfortunately this is super tricky. I cold not get it work properly.
Unfortunately the behavior of setting the `SystemUiOverlayStyle` is not consistent with the docs - at least on the iOS emulator (I have to assume it will behave the same on iOS...).
I tried:
- Set `SystemUiOverlayStyle.dark` in `app_bar_with_balance.dart`'s `AppBar` - so that this one is always dark. But unfortunately whenever I navigate to a child screen (e.g. Receive, CFD Order, ...) this resets `SystemUiOverlayStyle.light`. When navigating back the status bar is white and not visible. I assumed …
=> Align safe area

pubspec.lock, pubspec.yaml
Reverts itchysats/10101#422
fixes https://github.com/itchysats/10101/issues/441
Apparently we hit a regression bug that was already reported: https://github.com/flutter/flutter/issues/115962#issuecomment-1326560876
Note: I did go through the changelog before merging this and I did not see any indicator that we would run into trouble. Reverting for now, as there is no solution for `0.5.2` reported yet.
Note: Before I found the regression I actually gave replacing `/` with a specific `/wallet` route (and setting `/wallet` as initial route) a try, because in `/cfd-trading` and it's subroutes we did not have this problem even with `0.5.2`. But I experienced the same behavior.
=> Revert "chore(deps): bump go_router from 5.1.5 to 5.2.0"

.github/dependabot.yml
Temporarily disable until after the tournament.
I just commented the contents of the file and did not remove it.
Note: I did not disable `Dependabot security updates` and `Dependabot alerts` in the project settings, I think we can keep that.
=> Disable dependabot updates

.github/dependabot.yml
#449 was meant to disable dependabot. While doing so it caused an error because the file is now invalid. According to the [docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit), to disable dependabot temporarily, simply set the `open-pull-request-limit` to `0`.
=> fix:disable dependabot

Makefile, rust/src/config.rs
Fixes #438.
By default, taker app users will connect to the instance that runs the "stable" release.
By default, devs who run `NETWORK=testnet make run` or similar will connect to the instance that tracks `main`.
Devs will be able to connect to the stable version by specifying a value for the new environment variable e.g. 
```
NETWORK=testnet TESTNET_MAKER_INSTANCE=stable flutter run
```
=> Support connecting to both instances of the 10101 testnet maker

lib/balance.dart, lib/main.dart, lib/models/balance_model.dart, lib/wallet/open_channel.dart, lib/wallet/send_on_chain.dart, lib/wallet/wallet_dashboard.dart, maker/src/main.rs, maker/src/routes.rs
Fixes https://github.com/itchysats/10101/issues/352.
Depending on the situation we make use of different values:
- The balance widget now displays the total balance by default, but on hover one can see a tooltip with the breakdown between confirmed and pending.
- We use the confirmed on-chain balance to determine how much bitcoin they user can use to either open a channel or send on-chain.
- We use the total on-chain balance to determine if the initial deposit-bitcoin card should be rendered or not.
---
The first commit (https://github.com/itchysats/10101/commit/f56ab4895d9f2fbb20f4e36f00ccdc719cf970e4) was useful for testing so I decided to keep it around.
=> Take into account pending on-chain balance

maker/src/routes.rs, rust/sqlx-data.json, rust/src/api.rs, rust/src/db.rs, rust/src/lightning.rs, rust/src/wallet.rs
Sending and creating invoices had to change to `async` due to sqlx async nature.
=> feat: Persist lightning payments in sqlite database

rust/src/lightning.rs
That way we should be able to do multihop payments
untested, but I think it is needed for multi-hop payments.
=> chore: let's announce our channels.

lib/wallet/open_channel.dart
Liquidity is hard to get by. 500_000 from the taker side means 1mio sat from us, which is roughly what we get from the faucet per click.
=> chore: limit channel size

rust/src/config.rs
When this variable was not set (normal case for production),
it would print out 4 times every 20s announcing that it defaults to stable.
No need for logging this, the behaviour is well documented.
=> chore: Remove spammy log message

lib/app_bar_with_balance.dart, lib/balance.dart
The tooltip was created around the whole `Row`, which could cause trouble with opening the menu drawer in the `Bitcoin` wallet screen. The menu drawer was not properly clickable because the tooltip partly overlayed it.
Fixed by moving restricting the size of the `Row` to min (so it does not auto-expand) and moving the `Center` to the outside (it should not have been part of the `Balance` in the first place, the caller should decide how to layout the balance).
=> Restrict tooltip to size of Bitcoin balance

rust/migrations/20221201023908_open-channel-txid-to-ignore-tx.sql, rust/sqlx-data.json, rust/src/db.rs, rust/src/wallet.rs
fixes https://github.com/itchysats/10101/issues/477
This enables us to properly ignore the maker's funding even when the channel was closed already. We save the `open_channel_txid` upon the first time we are able to extract it from the channel. Once persisted we will always load it from the database for consecutive calls to sync the payment history.
=> Persist the channel opening `txid`

rust/src/api.rs
Clearly state the contract of the API, ie. not supporting empty values.
By being explicit that we don't support empty strings, we make it easier for
ourselves to notice such errors.
lack of this made me hunt for a bug in my code way longer than expected :(
=> chore: Ensure empty Strings are not passed into library

Cargo.lock, Cargo.toml
Fixes https://github.com/itchysats/10101/issues/475.
They were wrong because of a bug in our fork of `rust-lightning`: the channel amounts were not being updated after the custom output was removed.
We were already constructing the correct commitment transaction and because we only ever tested using force-close it looked like everything was working as intended!
=> Fix collaborative channel close amounts

android/app/src/main/AndroidManifest.xml, ios/Podfile.lock, lib/main.dart, lib/menu.dart, lib/utilities/feedback.dart, lib/wallet/wallet_dashboard.dart, macos/Flutter/GeneratedPluginRegistrant.swift, macos/Podfile.lock, pubspec.lock, pubspec.yaml
I found this pretty cool feedback package (https://pub.dev/packages/feedback), that will allow the user to draw on the screen, add a feedback and send his logs via email.
I guess we we will not use that on a major release, but to get feedback on a beta version, it's pretty useful.
Works on Android and ios (not couldn't test on ios, since the simulator does not come with an email client). Updating the text "What's wrong" is kind of possible, but really ugly through translations. I tried it, but stopped again as it wasn't worth it. If you are very much bothered about it feel free to create a follow up PR 🙈 .
I struggled a bit with where to put that button. I could think of the following.
1. always visible: but where, it shouldn't distract too much.
2. in the drawer: i guess pretty hidden …
=> feat: Add feedback button

lib/wallet/wallet_dashboard.dart
It's not a ListView anymore, but given the amount of the tiles there's no way to
overflow it on any mobile screen (tested on iPhone SE3)
=> fix: Center the dashboard tiles

Cargo.lock, Cargo.toml
The latest version of `bdk-ldk` removes some possibly buggy code which dealt with reorgs. Reorgs aren't very important in the context of a test application and we think that the possibly buggy code was causing unwarranted channel force-closes.
=> Ignore reorgs for the greater good

lib/wallet/qr_scan.dart, lib/wallet/send.dart
Fixes a minor regression that invoices can't be entered manually anymore. Also when looking into this bug, I figured it's probably nicer to have the QR code scanning icon next to the field. That way we could make it a reusable widget.
=> fix: Allow manual input of lightning invoice

rust/src/config.rs
Previous fix for the main testnet maker port accidentally broke regtest.
=> fix: Correctly choose required lightning port

lib/cfd_trading/cfd_offer.dart, lib/main.dart, lib/wallet/channel_change_notifier.dart, lib/wallet/drain_faucet.dart, lib/wallet/wallet_dashboard.dart, lib/wallet/wallet_lightning.dart, rust/src/api.rs, rust/src/connection.rs, rust/src/wallet.rs
Before that PR we where only depending on a timeout and a lightning balance. However, this led to several error messages as a lightning balance does not mean the channel is usable.
The PR introduces a sync of the channel state every 5 seconds representing the following 3 states:
1. Unavailable: No channel exists
2. Establishing: Channel exists but is not usable yet
3. Available: Channel exists and is usable
ebe4fb219a61b1802e673723916a77b8bad79ad4 fixes a regression after merging https://github.com/itchysats/10101/pull/483: we can not assume there is always a channel available. The taker was trying to reconnect constantly if no channel was available or if it was in creation. It's hard to distinguish between a good and a bad usable channel (as it might be in creation) - I am using the …
=> feat: Wait for channel to become available

lib/menu.dart
Makes it much easier to orient oneself in the app.
Sadly, ExpandedTile highlight ("Stacking") cannot be tweaked at all (always selected when expanded) , so I resorted to
also highlight the background of the active tile to make it stand out more.
=> feat: Highlight active page in the sidebar menu

Cargo.lock, lib/main.dart, lib/models/balance_model.dart, lib/wallet/close_channel.dart, rust/src/wallet.rs
Fixes #461.
The coins are correctly moved to a pending state, like we do with any other on-chain transaction.
The user is also informed about what to expect when closing the channel.
It's important to note that if the user runs into a force-closure for some other reason, the coins will also go into a pending state and be reflected in the overall on-chain balance, but it will take _hundreds_ of confirmations for the coins to be confirmed.
=> Update on-chain balance immediately after channel closure

lib/main.dart
Otherwise the logs attached in the feedback email don't help a lot.
all rust logs are still logged on debug - this should be fixed with https://github.com/itchysats/10101/issues/510
=> chore: Set log level to debug

lib/cfd_trading/cfd_offer.dart
#fixes https://github.com/itchysats/10101/issues/514
If we auto-open the keyboard the user is unable to navigate to other views (e.g. My CFDs) of the is screen.
Note: I don't think there is a better way to fix this without a bigger redesign of that screen - we could try to push the bottom menu up with the keyboard, but I think this will mess with the screen overall, because we don't have enough space to do that.
=> Do not auto-open the keyboard

rust/src/db.rs
would have been helpful when debugging
=> Log `txid` to be ignored that was saved in db

rust/src/wallet.rs
That will hopefully free up resources on the maker.
=> fix: Scoped wallet lock only for clone

Dockerfile
resolves #541
Tested locally on a mac with cross-compilation `TARGET_CC=x86_64-linux-musl-gcc cargo build --release --target x86_64-unknown-linux-musl`
=> fix: use latest distroless image

lib/cfd_trading/cfd_offer.dart, lib/wallet/action_card.dart, lib/wallet/channel_change_notifier.dart, lib/wallet/close_channel.dart, lib/wallet/wallet_dashboard.dart, lib/wallet/wallet_lightning.dart, rust/src/api.rs
- Uses `is_channel_ready` to distinguish between the establishing and disconnected state. According to the docs is_channel_ready will be true after the first confirmation and if there has been at least once a connection.
- Does not set a default channel state, preventing incorrect initial states upon start up.
- Adapts all warning messages accordingly to reflect the new disconnected channel state.
resolves #535
resolves #525
=> feat: Reflect disconnected maker

lib/main.dart, lib/models/seed_backup_model.dart, lib/wallet/seed.dart
Store the value in flutter shared preferences so that we don't prompt the user
to backup the seed after each restart.
=> fix: Persist seed backup state over restarts

lib/wallet/open_channel.dart
It's tricky to initialize it in the `init` function because we don't know the balance then. Thus, we set it based on the current maximum value if it is null.
Maybe there is a better solution to this, my brain is not working very well at the moment 😅
=> Set taker channel amount to current max

android/app/src/main/AndroidManifest.xml, lib/utilities/feedback.dart, lib/wallet/wallet_dashboard.dart
We unfortunately cannot attach images then, but the user can still send text feedback.
This helps to some extend, but does not solve https://github.com/itchysats/10101/issues/530 on my phone.
It might help with iOS - maybe you can give it a try @luckysori
=> Add fallback to `mailto` URI if `FlutterEmailSender` fails

lib/service_placeholders.dart
On screens with notch it might otherwise be partly covered.
I noticed that the placeholder screen does not properly make sure the balance is in the right place. This is what we did for the other screens to fix this.
=> Make sure balance looks good on all screens

Cargo.lock, lib/balance.dart, pubspec.lock, pubspec.yaml, rust/Cargo.toml
Displaying the total balance was a great idea, but it causes awkwardness because we then prominently display the maker amount being sent to the taker in the balance upon opening a channel. We cannot easily overcome this problem in the current version, so it's better to display only the confirmed balance prominently.
Additionally this causes awkwardness when we run into a channel force close, because the balance is not `0`, but when trying to open a new channel we can only use `0`, because our displayed balance is actually not usable.
---
@luckysori great composition, I think this is literally the only place I have to change :)
=> Display `confirmed` Bitcoin balance instead of `total`

macos/Podfile.lock
Building on macOS on latest `main` locks new dependencies.
=> chore: Update macOS Podfile

lib/app_bar_with_balance.dart, lib/wallet/wallet.dart, lib/wallet/wallet_change_notifier.dart
resolves #412 
If we are on the dashboard the button is not shown. If we are within lightning or bitcoin wallet the button displays home icon. If we are in any other screen that contains the balance on the top (trade, placeholder) we display a `wallet` icon.
This makes it easy to jump back to the dashboard.
=> Add back-to-dashboard button to the balance app-bar

maker/src/main.rs, maker/src/routes.rs, rust/src/api.rs, rust/src/cfd/open.rs, rust/src/cfd/settle.rs, rust/src/wallet.rs
We are never actually mutating the `Wallet` after it has been initialised, so it seems like we don't need a mutex to control access to this resource.
This makes the code a bit simpler and maybe faster since we won't be stuck waiting for some other function to release a mutex guard before we can use the `Wallet`.
---
I've tested it locally a few times and I didn't encounter any trouble.
=> Do not wrap `Wallet` in mutex

Dockerfile
It looks like this is the version which is being used on github ci and our distroless container does not provide it.
Resolves https://github.com/itchysats/10101/issues/541
=> fix: use image with glibc 2.35

.github/workflows/ci.yml
The big difference is that dependency updates will trigger a CI run for Rust part.
=> chore: Treat Cargo changes as Rust changes on CI
